name: 'Docker Buildx Build'
description: 'Build and push multi-platform Docker images with caching, secrets, SSH, and flexible build args'
inputs:
    repository:
        required: true
        description: 'GCP repository name (e.g., artifacts-0)'
    project-name:
        required: true
        description: 'GCP project name (e.g., portal, bootstrap, etc.)'
    app-name:
        required: true
        description: 'Application name (e.g., portal, validator)'
    dockerhub-username:
        required: true
        description: ''
    dockerhub-password:
        required: true
        description: ''
    context:
        default: '.'
        description: 'Build context path'
    dockerfile:
        default: 'Dockerfile'
        description: 'Path to Dockerfile'
    platforms:
        default: 'linux/amd64,linux/arm64'
        description: 'Platforms to build for (comma-separated)'
    ssh-enabled:
        default: 'false'
        description: 'Enable SSH forwarding into the Docker build (true/false)'
    extra-secrets:
        default: ''
        description: 'Multiline string of secrets in format id=value (one per line)'
    build-args:
        default: ''
        description: 'Multiline string of build arguments in format key=value (one per line)'
    cache-enabled:
        default: 'true'
        description: 'Enable caching (true/false)'
    cache-strategy:
        default: 'registry'
        description: 'Cache strategy: gha or registry'
runs:
    using: "composite"
    steps:
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v3
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
        - uses: docker/login-action@v3
          with:
              username: ${{ inputs.dockerhub-username }}
              password: ${{ inputs.dockerhub-password }}
        - name: Docker meta
          id: meta
          uses: docker/metadata-action@v5
          with:
              images: ${{ inputs.repository }}/${{ inputs.app-name }}
              tags: |
                  type=ref,event=branch
                  type=ref,event=pr
                  type=semver,pattern={{version}}
                  type=semver,pattern={{major}}.{{minor}}
                  type=sha
                  type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
        - name: Build and push
          uses: docker/build-push-action@v5
          with:
              context: ${{ inputs.context }}
              pull: 'true'
              file: ${{ inputs.dockerfile }}
              platforms: ${{ inputs.platforms }}
              push: true
              tags: ${{ steps.meta.outputs.tags }}
              labels: ${{ steps.meta.outputs.labels }}
              cache-from: ${{ inputs.cache-enabled == 'true' && (inputs.cache-strategy == 'gha' && 'type=gha' || format('type=registry,ref={0}/{1}:cache', inputs.repository, inputs.app-name)) || '' }}
              cache-to: ${{ inputs.cache-enabled == 'true' && (inputs.cache-strategy == 'gha' && 'type=gha,mode=max' || format('type=registry,ref={0}/{1}:cache,mode=max', inputs.repository, inputs.app-name)) || '' }}
              build-args: ${{ inputs.build-args }}
              ssh: ${{ inputs.ssh-enabled == 'true' && 'default' || '' }}
              secrets: ${{ inputs.extra-secrets }}
