import { MigrationInterface, QueryRunner } from 'typeorm'

export class AutoGeneratedIdColumn1689092742010 implements MigrationInterface {
    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(
            'ALTER TABLE "transaction" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()',
        )
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(
            'ALTER TABLE "transaction" ALTER COLUMN "id" DROP DEFAULT',
        )
    }
}
